pipeline {
  agent any

  stages {
    stage('Cleanup previous runs') {
      steps {
        sh('''#!/bin/bash -e
          rm -rf repo/
          rm -f new-releases.txt upstream-releases.txt skyos-releases.txt
        ''')
      }
    }
    stage('Check Fedora versions') {
      steps {
        echo 'Fetching all numeric Fedora versions...'
        sh('''#!/bin/bash -e
          curl -s https://pdc.fedoraproject.org/rest_api/v1/product-versions/ | jq -r '.results[].version' | grep -P '^\\d+$' | uniq | tee upstream-releases.txt
        ''')
      }
    }
    stage('Check SkyOS versions') {
      steps {
        sh('''#!/bin/bash -e
          git clone https://github.com/skylerspaeth/SkyOS.git repo/
          cd repo/
          echo 'Fetching SkyOS tags from GitHub repo...'
          git tag -l | tee ../skyos-releases.txt
        ''')
      }
    }
    stage('Detect new versions') {
      steps {
        sh('''#!/bin/bash -e
          diff upstream-releases.txt skyos-releases.txt | grep '^<' | cut -d' ' -f2 > new-releases.txt
          if [[ $(wc -l < new-releases.txt) -gt 0 ]]; then
            echo "New Fedora versions are available to build SkyOS for:"
            cat new-releases.txt
          fi
        ''')
      }
    }
  }
}
